version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "johngunnarsson"
    assignees:
      - "johngunnarsson"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group updates by dependency type
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      production-dependencies:
        patterns:
          - "next"
          - "react*"
          - "@supabase/*"
          - "stripe"
          - "plaid"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"